# Options: FLAT, SQLITE, MYSQL
DataStorage: SQLITE

# Information for mysql
MySQL:
  Host: ''
  # Default port is 3306
  Port: 3306 
  Database: ''
  Username: ''
  Password: ''
  # Max number of connections
  MaxConnections: 1
  # Maxium size of caching mysql
  # -1 for no limit
  # Affecting this value may affect performance
  MaxSize: -1
  # Table name prefix, for use with mutliple servers
  Prefix: ''
  #UseSSL: true
  
UseBungeeCoord: false
  
DefaultChannel: 'Global'

# Variables:
# %group%
# %player%
# %message%
# %nickname%
# Any placeholderapi placeholders supported as well
#
# Setting channel name to Town or Nation will enable towny chats
Channels:
  # Channel name
  Global:
    Format: '&a[G]%group% %player%: %message%'
    Permission: ''
    # WIP
    Bungeecoord: false
    # Setting to -1 means no distance limitation
    # Setting to 0 means global world chat
    # Sett to any other value means local chat (with 200 blocks for example)
    Distance: -1
    AutoJoin: true
    # This will also load channel commands for each alias
    Aliases:
    - g
    # Load main channel command (Channel name)
    LoadMainChannelCommand: true
    # Load commands for alaises
    LoadAliasChannelCommands: true
  Local:
    Format: '&a[L]%group% %player%: %message%'
    Permission: ''
    # WIP
    Bungeecoord: false
    Distance: 200
    AutoJoin: true
    Aliases:
    - l
  Staff:
    Format: '&a[S]%player%: %message%'
    Permission: 'AylaChat.Staff'
    # WIP
    Bungeecoord: false
    Distance: -1
    AutoJoin: true
    Aliases:
    - s
    
Format:
  # Format for /msg
  Message:
    Send: '%player% -> %toSend%: %message%'
    Receive: '%fromsender% -> %player%: %message%'
    NoReply: '&cNo one to reply to'
    SocialSpy: '[SC] %msg%'
    
  NoOneListening: '&cNo one is listening to you'

# Debug
Debug: false

# Extra Debug
# Only needed in extreme cases
ExtraDebug: false