# Options: FLAT, SQLITE, MYSQL
DataStorage: SQLITE

# Information for mysql
MySQL:
  Host: ''
  # Default port is 3306
  Port: 3306 
  Database: ''
  Username: ''
  Password: ''
  # Max number of connections
  MaxConnections: 1
  # Maxium size of caching mysql
  # -1 for no limit
  # Affecting this value may affect performance
  MaxSize: -1
  # Table name prefix, for use with mutliple servers
  Prefix: ''
  #UseSSL: true
  
# Requires a restart to take affect
UseBungeeCoord: false
  
DefaultChannel: 'Global'

# Variables:
# %group%
# %player%
# %message%
# %nickname%
# Any placeholderapi placeholders supported as well
#
# Setting channel name to Town or Nation will enable towny chats
Channels:
  # Channel name
  Global:
    Format: '&a[G]%group% %player%: %message%'
    Permission: ''
    # WIP
    Bungeecoord: false
    # Setting to -1 means no distance limitation
    # Setting to 0 means global world chat
    # Sett to any other value means local chat (with 200 blocks for example)
    Distance: -1
    AutoJoin: true
    # This will also load channel commands for each alias
    Aliases:
    - g
    # Load main channel command (Channel name)
    LoadMainChannelCommand: true
    # Load commands for alaises
    LoadAliasChannelCommands: true
  Local:
    Format: '&a[L]%group% %player%: %message%'
    Permission: ''
    # WIP
    Bungeecoord: false
    Distance: 200
    AutoJoin: true
    Aliases:
    - l
  Staff:
    Format: '&a[S]%player%: %message%'
    Permission: 'AylaChat.Staff'
    # WIP
    Bungeecoord: false
    Distance: -1
    AutoJoin: true
    Aliases:
    - s
    
Format:
  # Format for /msg
  Message:
    Send: '%player% -> %toSend%: %message%'
    Receive: '%fromsender% -> %player%: %message%'
    NoReply: '&cNo one to reply to'
    SocialSpy: '[SC] %msg%'
    # Rewards from 
    # https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards
    # Can be an actionbar, and way more!
    Rewards:
      Sound:
        # Enable or Disable Sound
        Enabled: true
        # Sound to play
        # Sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
        Sound: 'BLOCK_ANVIL_USE'
        # Volume
        # Range: 0.0 to 1.0
        Volume: 1.0
        # Pitch
        # Range: 0.0 to 1.0
        Pitch: 1.0
    
  Help:
    Title: '&3AylaChat Help'
    RequirePermission: true
    # AdvancedCore Commands can be viewed with /aylachat advancedcorehelp regardless of this option
    # Would recommend to have to this set to false to avoid showing unneeded commands
    ShowAdvancedCoreCommands: false
    
  ChannelSet: '&cSet channel to %channel%'
    
  NoOneListening: '&cNo one is listening to you'
  
  NoPerms: '&cYou do not have enough permission!'
  NotNumber: '&cError on &6%arg%&c, number expected!'
  HelpLine: '&3&l%Command% - &3%HelpMessage%'
  
  PrevPage: '&aPrevious Page'
  NextPage: '&aNext Page'
  
  Muted: '&cYou are currently muted'

# Debug
Debug: false

# Extra Debug
# Only needed in extreme cases
ExtraDebug: false