name: ${project.name}
version: ${project.version}
main: com.Ben12345rocks.AylaChat.Main
description: Highly Customizable Chat Plugin
author: Ben12345rocks
commands:
  aylachat:
    description: AylaChat Command
    aliases:
    - aylac
    - ach
  Msg:
    description: Msg another player
    aliases:
    - message
    - tell
  reply:
    description: Msg another player
    aliases:
    - r
  socialspy:
    description: Social spy
  clearchat:
    description: Clear chat
    aliases:
    - cc