name: ${project.name}
version: ${project.version}
main: com.Ben12345rocks.AylaChat.Main
description: Highly Customizable Chat Plugin
author: Ben12345rocks
commands:
  aylachat:
    description: AylaChat Command
  aylachatmsg:
    description: Msg
  Msg:
    description: Msg another player
    aliases:
    - message